name: Deploy to VM

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -Dtest=!ShelfSenseBeApplicationTests

    - name: Ensure SSH Directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Create SSH Key File
      run: |
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "echo 'SSH Connection Successful'"

    - name: Kill running process
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "sudo pkill -f ShelfSenseBE-0.0.1-SNAPSHOT.jar"

    - name: Delete old JAR file
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "sudo rm -f ShelfSenseBE-0.0.1-SNAPSHOT.jar"

    - name: Upload new JAR file
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key target/ShelfSenseBE-0.0.1-SNAPSHOT.jar azureuser@168.61.83.8:/home/azureuser/

    - name: Run new JAR file
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key azureuser@168.61.83.8 "
        SPRING_DATASOURCE_URL='${{ secrets.SPRING_DATASOURCE_URL }}' \
        SPRING_DATASOURCE_USERNAME='${{ secrets.SPRING_DATASOURCE_USERNAME }}' \
        SPRING_DATASOURCE_PASSWORD='${{ secrets.SPRING_DATASOURCE_PASSWORD }}' \
        SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }} \
        SERVER_PORT=${{ secrets.SERVER_PORT }} \
        nohup java -jar ShelfSenseBE-0.0.1-SNAPSHOT.jar > app.log 2>&1 & sleep 20 && pgrep -f ShelfSenseBE-0.0.1-SNAPSHOT.jar && echo 'JAR started successfully' || exit 1
        "
        

