name: Run Tests

on:
  pull_request:
    branches:
      - QA
      - main  # Specify the target branches for pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Eclipse Temurin distribution
          java-version: '19'       # Specify your Java version

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build and run tests
      - name: Build and test with Maven
        run: mvn clean test -Dtest=!ShelfSenseBeApplicationTests